# ===========================================
# Information Settings
# ===========================================

#navigation
menu:
  article: /
  archives: /archives
  tags: /tags
  about: /about
  # RSS: /atom.xml

  # favicon
favicon:

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
# toc: false

# Use copyright infomation
copyright: false
# license:

#Reword button or message
reward: false

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments: true
disqus: ruins-hes-house

# sub //Please just fill out ID.
sub:
  github: ruinshe
  weibo: ruinshe
  zhihu: ruins-he

#Friend link
friendLink:

# ===========================================
# Analytics
# ===========================================

google_analytics: UA-48752963-1
#baidu_analytics:

# ===========================================
# Theme Settings
# ===========================================

# lightbox
lightbox: true

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# mathJax (Powered by MathJax on https://www.mathjax.org/)
mathJax: false

# style
theme-style: gray

# Created Time
since: 2016

#about
self: Die!!!Die!!!!Die!!!!!!!!

# ===========================================
# Version
# ===========================================
version: 1.1

#theme_author: Co1MugX