# ===========================================
# Information Settings
# ===========================================

#navigation
menu:
  article: /
  archives: /archives
  tags: /tags
  about: /about
  # RSS: /atom.xml

# favicon
favicon:

# ===========================================
# Article Setting
# ===========================================

# Header Sign
header_sign: ∮

# Navigator in post
# toc: false

# Use copyright infomation
copyright:
  enable: false
  license:

#Reword button or message(fill your QRCode of any Pay.)
reward:
  enable: false
  alipay:
  wechat:
  paypal:

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments:
  enable: true
  disqus: ruins-hes-house
  uyan:
  duoshuo:
  netease:

# sub //Please just fill out ID.
sub:
#  facebook:
#  twitter:
#  instagram:
  weibo: ruinshe
  zhihu: ruins-he
  github: ruinshe
#  linkedin:

#Friend link
#friendLink:

# ===========================================
# Analytics
# ===========================================
google_analytics: UA-48752963-1
#baidu_analytics:

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: false

# ===========================================
# Theme Settings
# ===========================================

# lightbox
lightbox: true

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# mathJax (Powered by MathJax on https://www.mathjax.org/)
mathJax: true

# Created Time
since: 2012

#about
self: Die!!!Die!!!!Die!!!!!!!!

# ===========================================
# Search Settings
# ===========================================

# Search
search: true

greetings:
  morning:
  noon:
  after:
  night:
  midnight:

# greetings:
#   morning: '早上好，请问您需要点什么？'
#   noon: '记得午休吃饭，不着急看我的博客~'
#   after: '下午好，感谢查阅我的博客'
#   night: '您来我的博客看笑话当做休息嘛'
#   midnight: '我觉得大半夜就不要看啦'

# ===========================================
# Documents Styles
# ===========================================

# theme-style
theme-style: gray

# article-fonts
# default | Simsun | YaHei | Hel
fonts-style: default

# ===========================================
# Version
# ===========================================
version: 1.4

#theme_author: Co1MugX
